//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safety_Wheel {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class connection : global::System.Configuration.ApplicationSettingsBase {
        
        private static connection defaultInstance = ((connection)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new connection())));
        
        public static connection Default {
            get {
                return defaultInstance;
            }
        }
    }
}
